### PR TITLE
Nm testing and refining

### LINKED ISSUE #15: Navigate to login page TDD
As a user, when I click on the 'Login' button, I want to be able to see a form that will allow me to sign into my account.

- [ ] Since we can test by when a specific component shows up on the page, we can test when they click on the button that the Sign-In component shows up on the screen.
- [ ] Since we can test by specific components, decide and clarify if we need to have a full login page for routing of if the original modal idea would still work.

### LINKED ISSUE #16: Navigate to Movie Show TDD
As a user, when I click on a specific MovieTile, I want to be able to see a full detailed page of the movie.

- [ ] Test that the MovieShowPage component displays to the page when a user clicks on a MovieTile.

### LINKED ISSUE #35: TDD Sign-in Component
- [ ] Display feedback to the user if their login failed with wrong username and password.
- [ ] The component should be able to render.
- [ ] Should be able to log in a user with the correct credentials.

### LINKED ISSUE #36: TDD MovieMain Component
- [ ] This component should display all MovieTiles found after a fetch call.
- [ ] This component should throw an error message if the fetch call fails.

### LINKED ISSUE #37: TDD Navbar Component
- [ ] Should display on the App at all times.
- [ ] Should display a user name if they are logged in.
- [ ] Should not display a user name if no one is logged in.

### LINKED ISSUE #38: TDD MovieTile Component
- [ ] Should be able to display the information for a single movie.

### LINKED ISSUE #39: TDD App Component
- [ ] Should be able to render without crashing.
- [ ] Should be able to render that is is loading movies until movies have finished loading.

### LINKED ISSUE #50: Bug - propTypes
The propTypes for the components `MovieShowPage` and `Comments`, are set up to expect a `string` for userID. When there is no user logged in, the userID state it is set as an empty string by default, therefore it passes. However, when a user is logged in, that string is converted into a number data type, and the propTypes start throwing errors. When changing the propType for userID into a `number`, it will fail and throw errors when a user is logged out due to the default empty string data type when no user is logged in, but will be successful when a user is logged in.

### LINKED ISSUE #51: Enhancement - Reduced fetch calls
While writing the test for the Comments component. I learned a way that was causing some of our tests in other files to fail and a way to reduce fetch calls, improving app performance. 

When a user has submitted some new data (logging in, new comments, new rating, etc...), we call a fetch after our post to make sure that the data is in sync with each other. This second time of repeating the fetch call is what is causing the test to fail with an `undefined` reference, since we can only reference a particular set of data inside of a testing `it block` to be mocked once. 

To combat this, I removed the extra fetch call that was being used after a user posted a new comment and had it simply update state to render all previous comments as well as the new comment onto the page. The user will see no difference, as their new comment has showed up and state has been updated to reflect all of the most current data that would be on the server as well. 

Stopping that second fetch call and letting state update through setting state in react fixed the `undefined` reference having to attempt a 2nd mock call for new data within the same test. On the live app, the user will still see their new comment posted immediately. 

Leaving the page and coming back in will trigger the `componentDidMount` lifecycle method, which in turn will do the fetch call again, and show all comments on the page. In testing, I have learned that the 2nd fetch call is unnecessary and actually some of our tests to fail and not work as intended.

Let's use this new knowledge and fix any other areas where we are attempting to re-sync our state after a post that is an unnecessary fetch call and causing our tests, as well as react, to have unintended behavior.

### PR DESCRIPTION
**Pull request by nathanielmillard**
#### What’s this PR do?
-cleans up PropTypes
-refactors some props to allow for more sussict data transfer
-refactors tests to still pass after code updates
-writes new tests for FavoriteButton, MovieShowPage, and App
-some styling tweaks to improve user experience
    -especially in regards to the user signin page

#### Where should the reviewer start?
-This pr touches small lines on almost all of our files
-And fully creates test files for MovieShowPage and FavoriteButton

#### How should this be manually tested?
-run npm start and explore the page
-run npm test and see all 31 passing tests

#### Any background context you want to provide?
-This is finally resolving some feedback from @khalidwilliams early on the project
-Also resolves issues discussed in previous pr's leading up to this.

#### What are the relevant tickets?
- closes #50 
- closes #51 
- closes #16 
- closes #39 
- closes #38 
- closes #37 
- closes #36 
- closes #35 
- closes #15 

#### Screenshots (if appropriate):
-N/A
#### Questions:
-N/A

### CODE REVIEW

File: src/components/App/App.js [hunk 1]
```diff
@@ -13,25 +13,21 @@ import './App.scss';
 class App extends Component {
 	constructor() {
 		super();
-
 		this.state = {
-			currentUser: '',
-			id: '',
+			currentUser: {},
```
Comment (npdarrington) [inline src/components/App/App.js:17]: Great that this is an object now with all of the user's data. Makes it easier to pass around the data as we need to without having to expand extra room in state for it.

File: src/components/App/App.js [hunk 2]
```diff
@@ -91,7 +87,7 @@ class App extends Component {
 					/>
 					<Route exact path='/MovieShowPage/:movieID'
 					render={({match}) => {
-						const movieID = match.params.movieID
+						const movieID = parseInt(match.params.movieID)
```
Comment (npdarrington) [inline src/components/App/App.js:90]: This is really nice so we don't have to remember if we have to parseInt every time we need to use it as a prop.

File: src/components/Comments/Comments.js [hunk 3]
```diff
@@ -96,6 +96,6 @@ export default class Comments extends Component {
 }
 
 Comments.propTypes = {
-	movieID: propTypes.string.isRequired,
-	userID: propTypes.string,
+	movieID: propTypes.number.isRequired,
+	userName: propTypes.string,
```
Comment (npdarrington) [inline src/components/Comments/Comments.js:100]: Thank you for fixing propTypes bug.

**Review by npdarrington — APPROVED** [review]
Great job finalizing the testing with all the new changes and the clean up. Really makes the app run smoother and the user has a much more pleasant experience!
